# Generated by Django 3.2.24 on 2025-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jifen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrule',
            name='message_min_length',
            field=models.IntegerField(default=0, help_text='发言最小字数长度限制，0表示无限制'),
        ),
    ]
