# Generated by Django 3.2.24 on 2025-03-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jifen', '0002_pointrule_message_min_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrule',
            name='invite_daily_limit',
            field=models.IntegerField(default=0, help_text='每日邀请积分上限，0表示无限制'),
        ),
        migrations.CreateModel(
            name='DailyInviteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_date', models.DateField(help_text='统计日期')),
                ('invite_count', models.IntegerField(default=0, help_text='邀请人数')),
                ('points_awarded', models.IntegerField(default=0, help_text='获得积分')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('group', models.ForeignKey(help_text='群组ID', on_delete=django.db.models.deletion.CASCADE, to='jifen.group')),
                ('user', models.ForeignKey(help_text='用户ID', on_delete=django.db.models.deletion.CASCADE, to='jifen.user')),
            ],
            options={
                'verbose_name': '邀请每日统计',
                'verbose_name_plural': '邀请每日统计',
                'db_table': 'daily_invite_stats',
            },
        ),
        migrations.AddIndex(
            model_name='dailyinvitestat',
            index=models.Index(fields=['user'], name='daily_invit_user_id_8f23c7_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyinvitestat',
            index=models.Index(fields=['group'], name='daily_invit_group_i_5328fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyinvitestat',
            unique_together={('user', 'group', 'invite_date')},
        ),
    ]
