# Generated by Django 3.2.24 on 2025-03-23 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jifen', '0003_auto_20250322_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointrule',
            name='checkin_points_enabled',
            field=models.BooleanField(default=True, help_text='是否启用签到积分'),
        ),
    ]
