# Generated by Django 3.2.24 on 2025-03-23 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jifen', '0005_pointrule_points_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointrule',
            name='checkin_points_enabled',
        ),
        migrations.RemoveField(
            model_name='pointrule',
            name='invite_points_enabled',
        ),
        migrations.RemoveField(
            model_name='pointrule',
            name='message_points_enabled',
        ),
    ]
