# Generated by Django 3.2.24 on 2025-03-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jifen', '0006_auto_20250323_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='抽奖标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='抽奖描述')),
                ('created_at', models.DateTimeField(verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(verbose_name='更新时间')),
                ('signup_deadline', models.DateTimeField(verbose_name='报名截止时间')),
                ('draw_time', models.DateTimeField(verbose_name='开奖时间')),
                ('auto_draw', models.BooleanField(default=True, verbose_name='自动开奖')),
                ('notify_winners_privately', models.BooleanField(default=True, verbose_name='私聊通知中奖者')),
                ('announce_results_in_group', models.BooleanField(default=True, verbose_name='群内公布结果')),
                ('pin_results', models.BooleanField(default=False, verbose_name='置顶结果')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '进行中'), ('ENDED', '已结束'), ('CANCELED', '已取消')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='抽奖消息ID')),
                ('result_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='结果消息ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lotteries', to='jifen.user', verbose_name='创建者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotteries', to='jifen.group', verbose_name='所属群组')),
            ],
            options={
                'verbose_name': '抽奖活动',
                'verbose_name_plural': '抽奖活动',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LotteryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
            ],
            options={
                'verbose_name': '抽奖类型',
                'verbose_name_plural': '抽奖类型',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='奖项名称')),
                ('description', models.TextField(verbose_name='奖品内容')),
                ('quantity', models.IntegerField(default=1, verbose_name='中奖人数')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='奖品图片')),
                ('order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='choujiang.lottery', verbose_name='所属抽奖')),
            ],
            options={
                'verbose_name': '奖品',
                'verbose_name_plural': '奖品',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LotteryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('CHANNEL', '关注频道'), ('GROUP', '加入群组'), ('REGISTRATION_TIME', '账号注册时间'), ('NONE', '无条件')], max_length=20, verbose_name='条件类型')),
                ('channel_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='频道用户名')),
                ('channel_id', models.BigIntegerField(blank=True, null=True, verbose_name='频道ID')),
                ('group_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='群组用户名')),
                ('group_id', models.BigIntegerField(blank=True, null=True, verbose_name='群组ID')),
                ('min_registration_days', models.IntegerField(default=0, verbose_name='最小注册天数')),
                ('chat_identifier', models.CharField(blank=True, max_length=255, null=True, verbose_name='聊天标识符')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='choujiang.lottery', verbose_name='所属抽奖')),
            ],
            options={
                'verbose_name': '抽奖条件',
                'verbose_name_plural': '抽奖条件',
            },
        ),
        migrations.CreateModel(
            name='LotteryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '创建抽奖'), ('UPDATE', '更新抽奖'), ('JOIN', '参与抽奖'), ('DRAW', '开奖'), ('CANCEL', '取消抽奖')], max_length=20, verbose_name='操作类型')),
                ('timestamp', models.DateTimeField(verbose_name='操作时间')),
                ('details', models.TextField(blank=True, null=True, verbose_name='详细信息')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='choujiang.lottery', verbose_name='抽奖活动')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_logs', to='jifen.user', verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '抽奖日志',
                'verbose_name_plural': '抽奖日志',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='lottery',
            name='lottery_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotteries', to='choujiang.lotterytype', verbose_name='抽奖类型'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(verbose_name='参与时间')),
                ('is_winner', models.BooleanField(default=False, verbose_name='是否中奖')),
                ('lottery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='choujiang.lottery', verbose_name='所属抽奖')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winners', to='choujiang.prize', verbose_name='获得奖品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='jifen.user', verbose_name='参与用户')),
            ],
            options={
                'verbose_name': '参与者',
                'verbose_name_plural': '参与者',
                'unique_together': {('lottery', 'user')},
            },
        ),
    ]
