# Generated by Django 3.2.24 on 2025-04-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choujiang', '0002_auto_20250329_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='lottery_type',
            field=models.CharField(default='STANDARD', max_length=50, verbose_name='抽奖类型'),
        ),
    ]
