# Generated by Django 3.2.24 on 2025-04-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('choujiang', '0003_auto_20250401_2201'),
    ]

    operations = [
    ]
