# Generated by Django 3.2.24 on 2025-04-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choujiang', '0004_auto_20250404_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='specified_winners',
            field=models.TextField(blank=True, help_text='以逗号分隔的Telegram ID列表', null=True, verbose_name='指定中奖者ID列表'),
        ),
    ]
