# Generated by Django 3.2.24 on 2025-05-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choujiang', '0005_auto_20250409_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='media_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='媒体文件ID'),
        ),
        migrations.AddField(
            model_name='lottery',
            name='media_type',
            field=models.CharField(choices=[('PHOTO', '图片'), ('VIDEO', '视频'), ('NONE', '无')], default='NONE', max_length=10, verbose_name='媒体类型'),
        ),
        migrations.AddField(
            model_name='lottery',
            name='points_required',
            field=models.IntegerField(default=0, verbose_name='参与所需积分'),
        ),
        migrations.AddField(
            model_name='participant',
            name='points_spent',
            field=models.IntegerField(default=0, verbose_name='消耗积分'),
        ),
    ]
